import { Link } from 'react-router-dom';
import { ShoppingBag, Trash2, Minus, Plus, ArrowRight } from 'lucide-react';
import { useCart } from '../context/CartContext';
import { formatPrice } from '../utils/format';
import ProductImage from '../components/ProductImage';
import '../styles/cart.css';

export default function Cart() {
  const { lines, count, total, removeItem, setQuantity, clearCart } = useCart();
  return <section className="container page-section"><span className="eyebrow">LA TUA SELEZIONE</span><h1>Il tuo carrello.</h1>{!lines.length ? <div className="empty-state"><ShoppingBag size={50} strokeWidth={1} /><h2>La tua storia deve ancora iniziare.</h2><p>Esplora la collezione e scegli il segnatempo che ti somiglia.</p><Link to="/prodotti" className="button">Scopri gli orologi <ArrowRight size={18} /></Link></div> : <div className="cart-layout"><div><div className="cart-list-heading"><span>{count} articoli</span><button className="text-button" onClick={clearCart}>Svuota carrello</button></div>{lines.map((item) => <article className="cart-item" key={item.id}><Link to={`/prodotti/${item.id}`}><ProductImage product={item} /></Link><div className="cart-item-info"><span className="eyebrow">{item.collection}</span><Link to={`/prodotti/${item.id}`}><h2>{item.name}</h2></Link><p>{formatPrice(item.price)} / pezzo</p><div className="quantity-control"><button aria-label={`Diminuisci quantità ${item.name}`} disabled={item.quantity === 1} onClick={() => setQuantity(item.id, item.quantity - 1)}><Minus size={14} /></button><span aria-label={`Quantità ${item.name}`}>{item.quantity}</span><button aria-label={`Aumenta quantità ${item.name}`} disabled={item.quantity === 10} onClick={() => setQuantity(item.id, item.quantity + 1)}><Plus size={14} /></button></div></div><div className="cart-item-end"><strong>{formatPrice(item.price * item.quantity)}</strong><button className="icon-button" aria-label={`Rimuovi ${item.name}`} onClick={() => removeItem(item.id)}><Trash2 size={18} /></button></div></article>)}</div><aside className="cart-summary"><h2>Il riepilogo</h2><div><span>Subtotale</span><span>{formatPrice(total)}</span></div><div><span>Spedizione demo</span><span>Inclusa</span></div><div className="cart-total"><strong>Totale</strong><strong>{formatPrice(total)}</strong></div><p>IVA inclusa nel prezzo dimostrativo.</p><div className="checkout-note"><ShoppingBag size={20} /><span>Selezione salvata nel tuo browser.<br />Il checkout non è attivo in questa demo.</span></div><Link className="text-link" to="/prodotti">Continua la selezione <ArrowRight size={16} /></Link></aside></div>}</section>;
}
